apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kommonitor

bases:
  - importer/
  - data-management/
  - client-config/
  - web-client/
  - processing-engine/
  - processing-scheduler/
resources:
  - configmap.yaml
