apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kommonitor-processing-engine-storage
spec:
  storageClassName: "retained-ssd"
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
status: {}