kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: de-kommonitor-geocoder-admin-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  name: de-kommonitor-geocoder-admin # This is the link between k8s and the IAM role