 apiVersion: v1
 kind: Service
 metadata:
   name: geocode-proxy
   labels:
     app: geocode-proxy
 spec:
   selector:
     app: geocode-proxy
   ports:
   - name: http
     port: 8092
     targetPort: 8092
   type: NodePort

