# Use only for non-nginx ingress!
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: kommonitor-nginx
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        #include /etc/nginx/conf.d/*.conf;

        server {
          listen 80;

          location /ui/ {
            proxy_pass http://kommonitor-web-client:80/;
          }
          location /data-management/ {
            proxy_pass http://kommonitor-data-management:8085/;
          }
          location /data-importer/ {
            proxy_pass http://kommonitor-importer:8087/;
          }
          location /client-config/ {
            proxy_pass http://kommonitor-client-config:8088/;
          }
          location /data-processing/ {
            proxy_pass http://kommonitor-processing-engine:8086/;
          }
          location /spatial-processor/ {
            proxy_pass http://kommonitor-spatial-data-processor:8090/;
          }
          location / {
            # rewrite ^/$ /ui/ redirect;
            return 301 http://$host/ui/;
          }
        }

    }
