apiVersion: v1
kind: Service
metadata:
  name: kommonitor-nginx
  labels:
    app: kommonitor-nginx
spec:
  selector:
    app: kommonitor-nginx
  ports:
  - name: "http"
    port: 80
    targetPort: 80