apiVersion: v1
kind: Service
metadata:
  name: kommonitor-web-client
  labels:
    app: kommonitor-web-client
spec:
  selector:
    app: kommonitor-web-client
  ports:
  - name: "http"
    port: 80
    targetPort: 80