apiVersion: v1
kind: ConfigMap
metadata:
  name: kommonitor-data-management
data:
  #####################
  #      General      #
  #####################
  SERVER_MAX_HTTP_HEADER_SIZE: "48000"
  # adjust logging level [e.g. "INFO", "WARN", "ERROR"] - ERROR logs only errors 
  LOGGING_LEVEL_DE_HSBO_KOMMONITOR: INFO

  #####################
  #      Database     #
  #####################
  # host of database (i.e. Kubernetes service name when db runs in docker in same network;
  # else URL to database server)
  DATABASE_HOST: kommonitor-db
  # database name
  DATABASE_NAME: kommonitor-data
  # database port
  DATABASE_PORT: "5432"

  #####################
  # Spring Security   #
  #####################
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: https://demo.kommonitor.de/keycloak/realms/kommonitor-demo
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: https://demo.kommonitor.de/keycloak/realms/kommonitor-demo/protocol/openid-connect/certs

  #####################
  #     Keycloak      #
  #####################
  # client/resource id of data management component in Keycloak realm
  KEYCLOAK_RESOURCE: kommonitor-data-management

  #####################
  #    Swagger-UI     #
  #####################
  KOMMONITOR_SWAGGERUI_SERVER: https://demo.kommonitor.de/data-management

  SPRINGDOC_SWAGGERUI_CONFIGURL: /data-management/v3/api-docs/swagger-config
  SPRINGDOC_SWAGGERUI_URL: /data-management/v3/api-docs
  SPRINGDOC_SWAGGERUI_PATH: /api-docs
  SPRINGDOC_SWAGGERUI_OAUTH2REDIRECTURL: https://demo.kommonitor.de/data-management/swagger-ui/oauth2-redirect.html
  SPRINGDOC_SWAGGERUI_OAUTH_CLIENTID: kommonitor-data-management
  SPRINGDOC_SWAGGERUI_OAUTH_CLIENTSECRET: data-management-secret

  # name of the Keycloak role that is used as "administrator" role within KomMonitor granting rights to inspect
  # all data and perform all actions. This name of this role is configurable, but must be set to the equal value
  # within management and importer component as well as within Keycloak 
  KOMMONITOR_ROLES_ADMIN: kommonitor-creator
  # if true, will run a recreation of all database indicator views on startup (default false)
  KOMMONITOR_RECREATEALLVIEWSONSTARTUP: "false"