apiVersion: v1
kind: Service
metadata:
  name: kommonitor-data-management
  labels:
    app: kommonitor-data-management
spec:
  selector:
    app: kommonitor-data-management
  ports:
  - name: "http"
    port: 8085
    targetPort: 8085