apiVersion: v1
kind: ConfigMap
metadata:
  name: kommonitor-importer
data:
  #####################
  #      General      #
  #####################
  # setting to control coordinate axis order of coordinate systems. should be set to 'true',
  # to have X-coordinate as right value and Y-cooridnate as up value
  JAVA_OPTS: -Dorg.geotools.referencing.forceXY=true
  # connection entry point for internal communication with data management component
  KOMMONITOR_IMPORTER_DATAMANAGEMENTAPIURL: http://kommonitor-data-management:8085/management
  # connection entry point for internal communication with geocoder component
  # (you may usethe instance deployed at HSBO as it is configured here)
  KOMMONITOR_IMPORTER_GEOCODER_API_URL: https://geocoder.fbg-hsbo.de/geocoder

  #####################
  #     Keycloak      #
  #####################
  # depending on DNS Routing and Reverse Proxy setup a base path can be set here to access swagger-ui interface
  # (e.g. set '/importer' if https://kommonitor-url.de/importer works as entry point for localhost:8087)
  KOMMONITOR_SWAGGERUI_BASEPATH: data-importer
  # client/resource id of data management component in Keycloak realm
  KOMMONITOR_SWAGGER_UI_SECURITY_CLIENT_ID: kommonitor-importer
  # client/resource id of data management component in Keycloak realm
  KEYCLOAK_RESOURCE: kommonitor-importer