apiVersion: v1
kind: ConfigMap
metadata:
  name: kommonitor-importer
data:
  #####################
  #      General      #
  #####################
  # setting to control coordinate axis order of coordinate systems. should be set to 'true',
  # to have X-coordinate as right value and Y-cooridnate as up value
  JAVA_OPTS: -Dorg.geotools.referencing.forceXY=true
  # connection entry point for internal communication with data management component
  KOMMONITOR_IMPORTER_DATAMANAGEMENTAPIURL: http://kommonitor-data-management:8085/management
  # connection entry point for internal communication with geocoder component
  # (you may usethe instance deployed at HSBO as it is configured here)
  KOMMONITOR_IMPORTER_GEOCODER_API_URL: https://geocoder.fbg-hsbo.de/geocoder

  #####################
  # Spring Security   #
  #####################
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: https://demo.kommonitor.de/keycloak/realms/kommonitor-demo
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: https://demo.kommonitor.de/keycloak/realms/kommonitor-demo/protocol/openid-connect/certs

  #####################
  #     Keycloak      #
  # client/resource id of data management component in Keycloak realm
  KEYCLOAK_RESOURCE: kommonitor-importer

    #####################
  #    Swagger-UI     #
  #####################
  KOMMONITOR_SWAGGERUI_SERVER: https://demo.kommonitor.de/data-importer

  SPRINGDOC_SWAGGERUI_CONFIGURL: /data-importer/v3/api-docs/swagger-config
  SPRINGDOC_SWAGGERUI_URL: /data-importer/v3/api-docs
  SPRINGDOC_SWAGGERUI_PATH: /api-docs
  SPRINGDOC_SWAGGERUI_OAUTH2REDIRECTURL: https://demo.kommonitor.de/data-importer/swagger-ui/oauth2-redirect.html
  SPRINGDOC_SWAGGERUI_OAUTH_CLIENTID: kommonitor-importer
  SPRINGDOC_SWAGGERUI_OAUTH_CLIENTSECRET: importer-secret