apiVersion: v1
kind: Service
metadata:
  name: kommonitor-importer
  labels:
    app: kommonitor-importer
spec:
  selector:
    app: kommonitor-importer
  ports:
  - name: "http"
    port: 8087
    targetPort: 8087