apiVersion: v1
kind: ConfigMap
metadata:
  name: kommonitor-client-config
data:
  #####################
  #      General      #
  #####################
  PORT: "8088"  # port

  #####################
  #      Keycloak     #
  #####################
  KEYCLOAK_ENABLED: "true"                             # enable/disable role-based data access using Keycloak (true requires working Keycloak Setup and enforces that all other components must be configured to enable Keycloak as well)
  KEYCLOAK_REALM: kommonitor-demo                      # Keycloak realm name
  KEYCLOAK_AUTH_SERVER_URL: https://demo.kommonitor.de/keycloak/ # Keycloak URL
  KEYCLOAK_RESOURCE: kommonitor-client-config          # keycloak client name
  KOMMONITOR_ADMIN_ROLENAME: kommonitor-creator        # name of kommonitor admin role within keycloak - default is 'kommonitor-creator' 