apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kommonitor-client-config-storage
spec:
  storageClassName: "retained-ssd"
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
status: {}