apiVersion: v1
kind: Service
metadata:
  name: kommonitor-client-config
  labels:
    app: kommonitor-client-config
spec:
  selector:
    app: kommonitor-client-config
  ports:
  - name: "http"
    port: 8088
    targetPort: 8088