apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kommonitor-spatial-data-processor-storage
spec:
  storageClassName: "retained-ssd"
  resources:
    requests:
      storage: 6Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
status: {}