apiVersion: v1
kind: Service
metadata:
  name: kommonitor-spatial-data-processor
  labels:
    app: kommonitor-spatial-data-processor
spec:
  selector:
    app: kommonitor-spatial-data-processor
  ports:
  - name: "http"
    port: 8090
    targetPort: 8090