apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-db
spec:
  serviceName: keycloak-db
  selector:
    matchLabels:
      app: keycloak-db
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
      - name: keycloak-db
        image: postgres:15-master
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "16Mi"
            cpu: "1m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name: ALLOW_IP_RANGE
            value: 0.0.0.0/0
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: keycloak.db.user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-db
                key: keycloak.db.password
          - name: POSTGRES_DB
            value: keycloak-data
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: keycloak-db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: keycloak-db-data
    spec:
      storageClassName: retained-ssd
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
      accessModes:
      - "ReadWriteOnce"