apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nominatim-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 
  storageClassName: retained-ssd  

