apiVersion: v1
kind: Service
metadata:
  name: nominatim
  labels:
    app: nominatim
spec:
  selector:
    app: nominatim
  ports:
  - name: http1
    port: 8080
    targetPort: 8080
  type: NodePort